<?php
/*
    CHFEEDBACK.PHP Feedback Form PHP Script Ver 2.10.1
    Generated by thesitewizard.com's Feedback Form Wizard.
    Copyright 2000-2008 by Christopher Heng. All rights reserved.
    thesitewizard and thefreecountry are trademarks of Christopher Heng.

    Get the latest version, free, from:
        http://www.thesitewizard.com/wizards/feedbackform.shtml

        You can read the Frequently Asked Questions (FAQ) at:
                http://www.thesitewizard.com/wizards/faq.shtml

        I can be contacted at:
                http://www.thesitewizard.com/feedback.php
        Note that I do not normally respond to questions that have
        already been answered in the FAQ, so *please* read the FAQ.

    LICENCE TERMS

    1. You may use this script on your website, with or
    without modifications, free of charge.

    2. You may NOT distribute or republish this script,
    whether modified or not. The script can only be
    distributed by the author, Christopher Heng.

    3. THE SCRIPT AND ITS DOCUMENTATION ARE PROVIDED
    "AS IS", WITHOUT WARRANTY OF ANY KIND, NOT EVEN THE
    IMPLIED WARRANTY OF MECHANTABILITY OR FITNESS FOR A
    PARTICULAR PURPOSE. YOU AGREE TO BEAR ALL RISKS AND
    LIABILITIES ARISING FROM THE USE OF THE SCRIPT,
    ITS DOCUMENTATION AND THE INFORMATION PROVIDED BY THE
    SCRIPTS AND THE DOCUMENTATION.

    If you cannot agree to any of the above conditions, you
    may not use the script.

    Although it is not required, I would be most grateful
    if you could also link to thesitewizard.com at:

       http://www.thesitewizard.com/

*/

// ------------- CONFIGURABLE SECTION ------------------------

// $mailto - set to the email address you want the form
// sent to, eg
//$mailto                = "youremailaddress@example.com" ;

$mailto = 'info@debtfreelegacy.com' ;

// $subject - set to the Subject line of the email, eg
//$subject        = "Feedback Form" ;

$subject = "DebtFreeLegacy.com Online Book Order Form" ;

// the pages to be displayed, eg
//$formurl                = "http://www.example.com/feedback.html" ;
//$errorurl                = "http://www.example.com/error.html" ;
//$thankyouurl        = "http://www.example.com/thankyou.html" ;

$formurl = "http://www.debtfreelegacy.com/book/orderform.htm" ;
$errorurl = "http://www.debtfreelegacy.com/book/error.htm" ;
$thankyouurl = "http://www.debtfreelegacy.com/book/thanks.htm" ;

$uself = 0;
$email_is_required = 1;
$name_is_required = 1;

// -------------------- END OF CONFIGURABLE SECTION ---------------

$headersep = (!isset( $uself ) || ($uself == 0)) ? "\r\n" : "\n" ;
$Qty1 = $_POST['Qty1'] ;
$Qty2 = $_POST['Qty2'] ;
$Qty3 = $_POST['Qty3'] ;
$TotalBook = $_POST['TotalBook'] ;
$TotalTax = $_POST['TotalTax'] ;
$TotalShipping = $_POST['TotalShipping'] ;
$TotalPriority = $_POST['TotalPriority'] ;
$TotalAll = $_POST['TotalAll'] ;
$Name = $_POST['Name'] ;
$Address = $_POST['Address'] ;
$City = $_POST['City'] ;
$State = $_POST['State'] ;
$Zip = $_POST['Zip'] ;
$Email = $_POST['Email'] ;
$Phone1 = $_POST['Phone1'] ;
$Phone2 = $_POST['Phone2'] ;
$http_referrer = getenv( "HTTP_REFERER" );

if (!isset($_POST['Email'])) {
        header( "Location: $formurl" );
        exit ;
}
if (($email_is_required && (empty($Email) || !ereg("@", $Email))) || ($name_is_required && empty($Name))) {
        header( "Location: $errorurl" );
        exit ;
}
if ( ereg( "[\r\n]", $Name ) || ereg( "[\r\n]", $Email ) ) {
        header( "Location: $errorurl" );
        exit ;
}
if (empty($Email)) {
        $Email = $mailto ;
}

if (get_magic_quotes_gpc()) {
        $Comments = stripslashes( $Comments );
}

$messageproper =

        "This message was sent from:\n" .
        "$http_referrer\n" .
        "\n------------------------------------------------------------\n\n" .
        "Name: $Name\n" .
		"\n------------------------------------------------------------\n\n" .
        "Address: $Address\n" .
        "City: $City\n" .
        "State: $State\n" .
        "Zip: $Zip\n" .
		"\n------------------------------------------------------------\n\n" .
        "Email: $Email\n" .
        "Phone 1: $Phone1\n" .
		"Phone 2: $Phone2\n" .
        "\n------------------------ ORDER INFO ------------------------\n\n" .
        "Book Quantity: $Qty1\n" .
		"Book Total: $TotalBook\n" .
		"Tax Total: $TotalTax\n" .
		"Shipping Book Rate Quantity: $Qty2\n" .
		"Book Rate Shipping Total: $TotalShipping\n" .
		"Shipping Priority Mail Quantity: $Qty3\n" .
		"Priority Mail Shipping Total: $TotalPriority\n\n" .
		"GRAND TOTAL: $TotalAll\n" .
        "\n\n------------------------------------------------------------\n" ;

mail($mailto, $subject, $messageproper,
        "From: \"$Name\" <$Email>" . $headersep . "Reply-To: \"$Name\" <$Email>" . $headersep . "X-Mailer: chfeedback.php 2.10.1","-f$Email" );
header( "Location: $thankyouurl" );
exit ;

?>